[package]
name = "nickel-lang-package"
description = "The Nickel Package Manager (npm)"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[features]

[dependencies]
directories.workspace = true
git2 = { version = "0.18.3", default-features = false, features = ["https", "ssh", "vendored-openssl"] }
nickel-lang-core = { workspace = true, default-features = false }
serde.workspace = true
serde_json.workspace = true
tempfile = { workspace = true }
